# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a1d1cda5cc0b3afe080fb612e22d860969146119c61b5575d5dde0201402a99aa9b957b38ef9f40899ce4ea73a876c0f554d44f0f88606e63b56432defb9664

test:
  secret_key_base: b343c70b873985ac43e1c9f733fcf1c00e8f3487d45ed9510a3c7684f26bc3e38bd624895cd593390bfe9d3c15dfe6c024503936aa8bb164c3d21c7fe3beb7bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
